# Usa l'immagine di Grafana come base
FROM grafana/grafana:11.4.0
USER root
# Aggiorna i pacchetti e installa Python 3.9 con py3-pip e virtualenv
RUN apk update && apk add --no-cache \
    python3 \
    py3-pip \
    python3-dev \
    py3-virtualenv && \
    ln -sf python3 /usr/bin/python

# Crea un ambiente virtuale
RUN python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --upgrade pip

# Attiva l'ambiente virtuale di default
ENV PATH="/opt/venv/bin:$PATH"

# Imposta la working directory all'interno del container
WORKDIR /app

# Copia i file del progetto nella working directory
COPY app/ /app/
COPY requirements.txt /app/

# Installa le dipendenze
RUN pip install --no-cache-dir -r requirements.txt

USER grafana

# Comando per eseguire lo script
ENTRYPOINT ["sh", "-c", "python /app/setup_dashboard.py & exec ../run.sh"]



